on: workflow_dispatch
jobs:
  helm:
    name: Helm Charts
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit
          disable-sudo: true
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
